### ISSUE TITLE
Passing instance to tests

### ISSUE THREAD

**Issue by joaquimg** [JuliaOpt/MathOptInterfaceTests.jl#10]
Since we removed solvers, parameters must be added in the instance constructor.

These parameters must be passed to tests (Gurobi, CPLEX and Xpress need parameters do provide certificates).

Should we add keywords to tests?

We can always create a function taking no inputs, setting parameters and returning a new instance. Not a big fan of this...

**Comment by blegat** [comment]
Would you prefer that the function is `Gurobi.GurobiInstance` instead of `() -> Gurobi.GurobiInstance(arg=val)` and that we add the parameters to be passed in the config ?

**Comment by joaquimg** [comment]
I am not sure what I prefer anymore.

The good thing of having args in config is that the “instance” function is always the same, that might be a slight better organization than what I did in all LQOI solvers. 

Varying these solver parameters typically make the tests vary.

**Comment by blegat** [comment]
This is fixed by https://github.com/JuliaOpt/MathOptInterfaceTests.jl/pull/44 since we now pass the instance directly.
