### ISSUE TITLE
config option for copy-only solver

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/MathOptInterfaceTests.jl#22]
Tests need to be updated for solvers that support `copy!` but do not support `addconstraint!`. We can do this as an option in `TestConfig`. In this case, we'd load into an `Instance` first then `copy!` to the solver.

**Comment by blegat** [comment]
Why not have the solver do `contlinear(() -> InstanceManager(SCSInstance()), config)` ?

**Comment by mlubin** [comment]
@blegat the solver shouldn't have to do that, but the implementation of the config option could choose to.

**Comment by mlubin** [comment]
> the implementation of the config option could choose to

Or maybe not. It seems more complex than necessary, because it now forces the solver writer to understand `InstanceManager` in order to debug test failures.

**Comment by blegat** [comment]
@mlubin It seems we converged in https://github.com/JuliaOpt/MathOptInterfaceUtilities.jl/pull/65 to the solution where the solver is responsible to wrap it inside an `InstanceManager` with the special constructor `InstanceManager(instance, solver)`.
Ok to close ?

**Comment by mlubin** [comment]
This isn't an ideal outcome, but we have higher priorities for now.
Could we add a README for solver-wrapper authors on how to use MOIT?

**Comment by blegat** [comment]
Yes, we should add that
