### ISSUE TITLE
isapprox

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/MathOptInterfaceTests.jl#33]
I'm pretty sure I introduced this myself, but now I'm finding our use of `isapprox` a bit confusing. (https://github.com/JuliaOpt/MathOptInterfaceTests.jl/pull/32#discussion_r158653716)

1. Shouldn't it be defined in MOIT instead of MOIU?
2. For `VectorOfVariables` we should use equality instead of `isapprox`.

**Comment by blegat** [comment]
1. Defining it in MOIT will make it possible to drop the MOIU dependency so it is nice
2. I am ok with this. I guess the same treatment applies to `SingleVariable`.
